Correção controladores
codecatss/API-BD2 pull request #5
Opened 2023-04-13 22:20 UTC by DankoCaboski

Adicionados os controladores das telas de home do colaborador, gestor e do administrador.

2023-04-13 23:04 UTC, larissa-fernanda approved these changes

2023-04-15 19:15 UTC, larissa-fernanda requested changes
Resolva os conflitos 😸

2023-04-16 02:41 UTC, DankoCaboski commented
Correções realizadas

2023-04-17 14:54 UTC, larissa-fernanda approved these changes

2023-04-17 16:53 UTC, NicSouza approved these changes

2023-04-17 23:02 UTC, merged